/**
 * Arena constants - shared between frontend and backend
 */

export const ARENA_CONSTANTS = {
  PROMPT_MIN_LENGTH: 3,
  PROMPT_MAX_LENGTH: 8000,
  MODEL_MIN_SELECT: 2,
  MODEL_MAX_SELECT: 5,
  OPENROUTER_TIMEOUT_MS: 60000,
  // 2048 tokens covers most conversational responses without cutting off mid-sentence.
  OPENROUTER_MAX_TOKENS: 2048,
  COMPARE_RATE_LIMIT_WINDOW_MS: 60_000,
  COMPARE_RATE_LIMIT_MAX_REQUESTS: 10,
  VOTE_RATE_LIMIT_WINDOW_MS: 60_000,
  VOTE_RATE_LIMIT_MAX_REQUESTS: 30,
  // Avatar uploads hit Supabase Storage (paid egress/writes); keep tight per user.
  AVATAR_RATE_LIMIT_WINDOW_MS: 60_000,
  AVATAR_RATE_LIMIT_MAX_REQUESTS: 5,
  // Email changes send confirmation messages to old and new addresses; keep strict.
  EMAIL_CHANGE_RATE_LIMIT_WINDOW_MS: 3_600_000,
  EMAIL_CHANGE_RATE_LIMIT_MAX_REQUESTS: 3,
  // GET /api/models is a cheap read; 60 req/min is generous but prevents scraping.
  MODELS_RATE_LIMIT_WINDOW_MS: 60_000,
  MODELS_RATE_LIMIT_MAX_REQUESTS: 60,
  // History is a cheap authenticated read; mirror the models budget.
  HISTORY_RATE_LIMIT_WINDOW_MS: 60_000,
  HISTORY_RATE_LIMIT_MAX_REQUESTS: 60,
  HISTORY_PAGE_SIZE_DEFAULT: 20,
  HISTORY_PAGE_SIZE_MAX: 50,
  // Code Arena Lite constants (v0.7)
  CODE_COMPARE_RATE_LIMIT_WINDOW_MS: 60_000,
  CODE_COMPARE_RATE_LIMIT_MAX_REQUESTS: 8,

  // Guest-specific tighter limits (anti-abuse)
  GUEST_COMPARE_RATE_LIMIT_WINDOW_MS: 60_000,
  GUEST_COMPARE_RATE_LIMIT_MAX_REQUESTS: 5,
  GUEST_CODE_COMPARE_RATE_LIMIT_WINDOW_MS: 60_000,
  GUEST_CODE_COMPARE_RATE_LIMIT_MAX_REQUESTS: 3,
  CODE_PROMPT_MIN_LENGTH: 10,
  CODE_PROMPT_MAX_LENGTH: 6000,
  CODE_MODEL_MIN_SELECT: 2,
  CODE_MODEL_MAX_SELECT: 3,

  // Code Run (v1.7) - Piston sandbox execution
  CODE_RUN_MAX_CHARS: 10_000,
  CODE_RUN_TIMEOUT_MS: 5_000,
  CODE_RUN_RATE_LIMIT_MAX: 10,
  CODE_RUN_RATE_LIMIT_WINDOW_MS: 60_000,
  PISTON_API_URL: "https://emkc.org/api/v2/piston/execute",

  // Image Arena constants (v1.8)
  IMAGE_MAX_PROMPT_CHARS: 1000,
  IMAGE_MAX_MODELS: 3,
  IMAGE_RATE_LIMIT_MAX: 5,
  IMAGE_RATE_LIMIT_WINDOW_MS: 60_000,
  OPENROUTER_IMAGE_API_URL: "https://openrouter.ai/api/v1/images/generations",
  IMAGE_SIZE: "1024x1024",

  // Judge Mode constants (v1.3)
  JUDGE_RATE_LIMIT_WINDOW_MS: 60_000,
  JUDGE_RATE_LIMIT_MAX_REQUESTS: 3,
  GUEST_JUDGE_RATE_LIMIT_WINDOW_MS: 60_000,
  GUEST_JUDGE_RATE_LIMIT_MAX_REQUESTS: 1,
  JUDGE_MAX_TOKENS: 800,
  // Primary: Nemotron reasoning model (1M context, ideal for judging)
  JUDGE_PRIMARY_MODEL_ID: "nvidia/nemotron-3-ultra-550b-a55b:free",
  // Fallback: reliable general model
  JUDGE_FALLBACK_MODEL_ID: "meta-llama/llama-3.3-70b-instruct:free",
  JUDGE_RESPONSE_TRUNCATE_CHARS: 1500,
};

export const MODE_SLUG_PROMPT_ARENA = "prompt-arena";
export const MODE_SLUG_CODE_ARENA = "code-arena";
export const ALLOWED_MODE_SLUGS = [MODE_SLUG_PROMPT_ARENA, MODE_SLUG_CODE_ARENA] as const;

export type ArenaModeSlug = (typeof ALLOWED_MODE_SLUGS)[number];

// Code Arena supported languages and frameworks (v0.7)
export const CODE_ARENA_LANGUAGES = [
  "TypeScript",
  "JavaScript",
  "Python",
  "SQL",
  "Go",
  "Rust",
  "Java",
  "C#",
  "PHP",
  "Ruby",
] as const;

export type CodeArenaLanguage = (typeof CODE_ARENA_LANGUAGES)[number];

export const CODE_ARENA_FRAMEWORKS: Record<string, string[]> = {
  TypeScript: ["Next.js", "React", "Express", "NestJS", "Supabase", "Bun"],
  JavaScript: ["Next.js", "React", "Express", "Node.js", "Vue", "Nuxt"],
  Python: ["FastAPI", "Django", "Flask", "SQLAlchemy", "Pandas"],
  SQL: ["PostgreSQL", "MySQL", "SQLite"],
  Go: ["Gin", "Echo", "Fiber"],
  Rust: ["Axum", "Actix"],
  Java: ["Spring Boot"],
  "C#": ["ASP.NET Core"],
  PHP: ["Laravel"],
  Ruby: ["Rails"],
};

export const {
  PROMPT_MIN_LENGTH,
  PROMPT_MAX_LENGTH,
  MODEL_MIN_SELECT,
  MODEL_MAX_SELECT,
  OPENROUTER_TIMEOUT_MS,
  OPENROUTER_MAX_TOKENS,
  COMPARE_RATE_LIMIT_WINDOW_MS,
  COMPARE_RATE_LIMIT_MAX_REQUESTS,
  VOTE_RATE_LIMIT_WINDOW_MS,
  VOTE_RATE_LIMIT_MAX_REQUESTS,
  AVATAR_RATE_LIMIT_WINDOW_MS,
  AVATAR_RATE_LIMIT_MAX_REQUESTS,
  EMAIL_CHANGE_RATE_LIMIT_WINDOW_MS,
  EMAIL_CHANGE_RATE_LIMIT_MAX_REQUESTS,
  MODELS_RATE_LIMIT_WINDOW_MS,
  MODELS_RATE_LIMIT_MAX_REQUESTS,
  HISTORY_RATE_LIMIT_WINDOW_MS,
  HISTORY_RATE_LIMIT_MAX_REQUESTS,
  HISTORY_PAGE_SIZE_DEFAULT,
  HISTORY_PAGE_SIZE_MAX,
  CODE_COMPARE_RATE_LIMIT_WINDOW_MS,
  CODE_COMPARE_RATE_LIMIT_MAX_REQUESTS,
  CODE_PROMPT_MIN_LENGTH,
  CODE_PROMPT_MAX_LENGTH,
  CODE_MODEL_MIN_SELECT,
  CODE_MODEL_MAX_SELECT,
  GUEST_COMPARE_RATE_LIMIT_WINDOW_MS,
  GUEST_COMPARE_RATE_LIMIT_MAX_REQUESTS,
  GUEST_CODE_COMPARE_RATE_LIMIT_WINDOW_MS,
  GUEST_CODE_COMPARE_RATE_LIMIT_MAX_REQUESTS,
} = ARENA_CONSTANTS;

export const {
  CODE_RUN_MAX_CHARS,
  CODE_RUN_TIMEOUT_MS,
  CODE_RUN_RATE_LIMIT_MAX,
  CODE_RUN_RATE_LIMIT_WINDOW_MS,
  PISTON_API_URL,
} = ARENA_CONSTANTS;

export const {
  IMAGE_MAX_PROMPT_CHARS,
  IMAGE_MAX_MODELS,
  IMAGE_RATE_LIMIT_MAX,
  IMAGE_RATE_LIMIT_WINDOW_MS,
  OPENROUTER_IMAGE_API_URL,
  IMAGE_SIZE,
} = ARENA_CONSTANTS;

export const {
  JUDGE_RATE_LIMIT_WINDOW_MS,
  JUDGE_RATE_LIMIT_MAX_REQUESTS,
  GUEST_JUDGE_RATE_LIMIT_WINDOW_MS,
  GUEST_JUDGE_RATE_LIMIT_MAX_REQUESTS,
  JUDGE_MAX_TOKENS,
  JUDGE_PRIMARY_MODEL_ID,
  JUDGE_FALLBACK_MODEL_ID,
  JUDGE_RESPONSE_TRUNCATE_CHARS,
} = ARENA_CONSTANTS;
