/**
 * Arena constants - shared between frontend and backend
 */

export const ARENA_CONSTANTS = {
  PROMPT_MIN_LENGTH: 3,
  PROMPT_MAX_LENGTH: 8000,
  MODEL_MIN_SELECT: 2,
  MODEL_MAX_SELECT: 3,
  OPENROUTER_TIMEOUT_MS: 30000,
};

export const {
  PROMPT_MIN_LENGTH,
  PROMPT_MAX_LENGTH,
  MODEL_MIN_SELECT,
  MODEL_MAX_SELECT,
  OPENROUTER_TIMEOUT_MS,
} = ARENA_CONSTANTS;
