/**
 * Arena constants - shared between frontend and backend
 */

export const ARENA_CONSTANTS = {
  PROMPT_MIN_LENGTH: 3,
  PROMPT_MAX_LENGTH: 8000,
  MODEL_MIN_SELECT: 2,
  MODEL_MAX_SELECT: 3,
  OPENROUTER_TIMEOUT_MS: 60000,
  OPENROUTER_MAX_TOKENS: 1000,
  COMPARE_RATE_LIMIT_WINDOW_MS: 60_000,
  COMPARE_RATE_LIMIT_MAX_REQUESTS: 10,
  VOTE_RATE_LIMIT_WINDOW_MS: 60_000,
  VOTE_RATE_LIMIT_MAX_REQUESTS: 30,
};

export const MODE_SLUG_PROMPT_ARENA = "prompt-arena";
export const ALLOWED_MODE_SLUGS = [MODE_SLUG_PROMPT_ARENA] as const;

export type ArenaModeSlug = (typeof ALLOWED_MODE_SLUGS)[number];

export const {
  PROMPT_MIN_LENGTH,
  PROMPT_MAX_LENGTH,
  MODEL_MIN_SELECT,
  MODEL_MAX_SELECT,
  OPENROUTER_TIMEOUT_MS,
  OPENROUTER_MAX_TOKENS,
  COMPARE_RATE_LIMIT_WINDOW_MS,
  COMPARE_RATE_LIMIT_MAX_REQUESTS,
  VOTE_RATE_LIMIT_WINDOW_MS,
  VOTE_RATE_LIMIT_MAX_REQUESTS,
} = ARENA_CONSTANTS;
